name: Bug report
description: Create a report to help us improve the DepNav app
title: "[BUG] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Do not create a report if the bug isn't reproducible.**

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    id: hardware-model
    attributes:
      label: Hardware model
      placeholder: e.g. iPhone 13 Pro
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. iOS 17.0
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: App version
      placeholder: e.g. 1.2.3
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
